### ISSUE TITLE
add cypher-query-builder

### ISSUE THREAD

**Issue by Alfredo3232** [CodeFusion508/codeFusion-backend#9]
# Priority: High

### User Story

    As a developer,
    I want to be able to build queries, easy and quickly,
    so that I can properly build quieries and not spend too much development time on building large queries.

### Acceptance Criteria

    Given that I, a developer, 
    when I want to build some queries, 
    then I should be able to use this ilibararies to build it for me

**Comment by pancho508** [comment]
We need to think about his a little more. 
From experience up till now for me. 
This lib has added a layer of complexity that seems too costly and it we might need to start thinking if we actually need this lib. 
Given that if we create the cypher queries from scratch it would give us more experience on building them.
